name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.3.app
      - name: Run tests
        run: |
          xcodebuild test \
            -workspace .github/package.xcworkspace \
            -scheme Validations \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.5"
          xcodebuild test \
            -workspace .github/package.xcworkspace \
            -scheme Validations \
            -destination "platform=macOS"

